# frozen_string_literal: true

module TurboTests
  class Shim
    Result = Struct.new(:status, :path, :message, :exit_code, keyword_init: true)

    DEFAULT_RELATIVE_PATH = File.join("bin", "turbo_tests")
    MANAGED_MARKER = "Generated by turbo_tests2 shim install"

    class << self
      def install(project_root: Dir.pwd, path: nil)
        new(project_root: project_root, path: path).install
      end

      def remove(project_root: Dir.pwd, path: nil)
        new(project_root: project_root, path: path).remove
      end
    end

    attr_reader :project_root, :path

    def initialize(project_root: Dir.pwd, path: nil)
      @project_root = File.expand_path(project_root)
      @path = File.expand_path(path || DEFAULT_RELATIVE_PATH, @project_root)
    end

    def install
      existing_managed = false
      if File.exist?(path)
        existing = File.read(path)
        return result(:unchanged, "Shim already installed at #{display_path}.", 0) if existing == rendered_content
        return result(:conflict, "Refusing to overwrite unmanaged file at #{display_path}.", 1) unless managed_content?(existing)
        existing_managed = true
      end

      FileUtils.mkdir_p(File.dirname(path))
      File.write(path, rendered_content)
      FileUtils.chmod(0o755, path)

      result(existing_managed ? :updated : :installed, "Installed turbo_tests shim at #{display_path}.", 0)
    end

    def remove
      return result(:missing, "No shim found at #{display_path}.", 0) unless File.exist?(path)

      content = File.read(path)
      return result(:conflict, "Refusing to remove unmanaged file at #{display_path}.", 1) unless managed_content?(content)

      File.delete(path)
      result(:removed, "Removed turbo_tests shim at #{display_path}.", 0)
    end

    private

    def display_path
      path.sub(%r{\A#{Regexp.escape(project_root)}/?}, "")
    end

    def managed_content?(content)
      content.include?(MANAGED_MARKER)
    end

    def rendered_content
      <<~SH
        #!/usr/bin/env sh
        # #{MANAGED_MARKER}
        exec bundle exec turbo_tests2 "$@"
      SH
    end

    def result(status, message, exit_code)
      Result.new(status: status, path: path, message: message, exit_code: exit_code)
    end
  end
end
