# frozen_string_literal: true

RSpec.describe TurboTests::Shim do
  around do |example|
    Dir.mktmpdir do |dir|
      @project_root = dir
      example.run
    end
  end

  attr_reader :project_root

  it "installs a managed bin/turbo_tests shim" do
    result = described_class.install(project_root: project_root)

    expect(result.exit_code).to eq(0)
    expect(result.status).to eq(:installed)
    expect(File.read(File.join(project_root, "bin/turbo_tests"))).to include("Generated by turbo_tests2 shim install")
  end

  it "is idempotent when the managed shim is already current" do
    described_class.install(project_root: project_root)

    result = described_class.install(project_root: project_root)

    expect(result.exit_code).to eq(0)
    expect(result.status).to eq(:unchanged)
  end

  it "refuses to overwrite an unmanaged bin/turbo_tests file" do
    FileUtils.mkdir_p(File.join(project_root, "bin"))
    File.write(File.join(project_root, "bin/turbo_tests"), "#!/usr/bin/env sh\necho custom\n")

    result = described_class.install(project_root: project_root)

    expect(result.exit_code).to eq(1)
    expect(result.status).to eq(:conflict)
  end

  it "removes a managed shim" do
    described_class.install(project_root: project_root)

    result = described_class.remove(project_root: project_root)

    expect(result.exit_code).to eq(0)
    expect(result.status).to eq(:removed)
    expect(File).not_to exist(File.join(project_root, "bin/turbo_tests"))
  end
end
